### Listar clientes 
GET http://localhost:5212/clientes/listar

##Cadastrar cliente
POST http:localhost:5212/api/produto/cadastrar
Connection-Content-Type: applicatino/json
{
  "Nome" : "Ana",
  "Email" : "ana@gmail.com"
}